name: publish

on:
    push:
        branches: [main]
    release:
        types: [published]

jobs:
    publish:
        runs-on: ubuntu-22.04
        timeout-minutes: 30

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Set up Deno
              uses: denoland/setup-deno@v1

            - name: Format
              run: deno fmt

            - name: Type check
              run: deno task test

            - name: Publish (dry run)
              if: github.event_name == 'push'
              run: deno publish --allow-dirty --dry-run

            - name: Publish (real)
              if: github.event_name == 'release'
              run: deno publish --allow-dirty

            - name: Build for NPM
              run: deno task build

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"

            - name: NPM (dry run)
              if: github.event_name == 'push'
              run: npm publish --dry-run

            - name: NPM (real)
              if: github.event_name == 'release'
              run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
